variable vpc_cidr_block {}
variable env_prefix {}
variable avail_zone {}
variable my_ip {}
variable instance_type {}
variable ssh_public_key_file_location {}
variable ssh_private_key_file_location {}
variable subnet_cidr_block {}
variable image_name {}